const LANGUAGES = {

  //English
  en: {
    // ===== App / header =====
    appTitle: "PM2040 – UF2 Multi-ROM Patcher",
    language: "Language",
    theme: "Theme",
    dark: "Dark",
    light: "Light",

    // ===== Settings =====
    nameSource: "Name source",
    fromFilename: "From filename",
    fromBinary: "From binary",
    uppercase: "Uppercase",

    // ===== Games section =====
    games: "Games",
    dropzone: "Drag & drop .min here or",
    chooseFiles: "Choose files",
    gamesHint: "Max games: 20. Max file size: 512 KiB.",

    // ===== Firmware =====
    firmware: "Base firmware (UF2)",
    reloadFirmware: "Reload firmware",
    chooseAnother: "Choose another…",
    fwChecking: "Base firmware: checking…",
    fwLoaded: "Base firmware: loaded",
    fwLoadedZip: "Base firmware: loaded (zip)",
    fwLoadedZipNoUF2: "ZIP found but no UF2 inside",
    fwLocalPage: "Base firmware: local page — pick file manually",
    fwNotFound: "Base firmware: not found",
    fwPickManual: "Pick a base firmware manually.",
    fwFileProtocolWarning: "Because this page is opened from your disk (file://), browsers block auto-loading. Click “Pick another…” or “Reload” to choose PM2040.uf2.",

    fwLoadedFrom: "Loaded from",
    fwLoadedDefault: "Loaded",
    fwLoadedManual: "Base firmware: loaded (manual)",
    fwLoadedFile: "Loaded",
    fwFileModeAlert: "Open from disk detected. Please choose a UF2 with “Pick another…” or click “Reload” to open the file picker.",
    fwLoadRequired: "Load base firmware first (PM2040.uf2 or pick manually).",

    // ===== Game list =====
    gameList: "Game list",
    gameListHint: "Reorder by dragging the handle (≡). Names may exceed 14 chars (will be truncated on patch). Invalid state shows red + hint. Use the global selector to switch all name sources.",
    cover: "Cover",
    file: "File",
    displayName: "Display name",
    actions: "Actions",
    dragToReorder: "Drag to reorder",
    remove: "Remove",
    charsetHint: "Charset enforced; length > 14 allowed visually but truncated when patching.",

    // ===== Buttons =====
    clear: "Clear",
    patch: "Patch",

    // ===== Footer =====
    footerText: "Created: 2026-06 · Generated by GPT-5.",

    // ===== Validation / alerts =====
    nameTooShort: "Name must be at least 1 character.",
    nameTooLong: "Name exceeds {max} characters (will be truncated).",
    charNotAllowed: 'Character "{ch}" is not allowed.',

    maxGamesReached: "You can only add up to {max} games. Extra files will be ignored.",
    fileTooLarge: '"{file}" exceeds 512 KiB and was skipped.',
    noGamesAdded: "Add at least one .min game.",
    emptyNames: "Some names are empty.",
    uf2Only: "Only .uf2 is allowed.",
    injectRomMissing: "injectROMs(...) not found. Please include patcher.js before this UI script.",
    patchFailed: "Patch failed. See console for details.",

    resumeSkip: "[resume-skip]",
    resumePatched: "[resume-patched]"
  },


  //German
  de: {
    appTitle: "PM2040 – UF2 Multi-ROM Patcher",
    language: "Sprache",
    theme: "Design",
    dark: "Dunkel",
    light: "Hell",

    nameSource: "Namensquelle",
    fromFilename: "Aus Dateiname",
    fromBinary: "Aus ROM",
    uppercase: "Großbuchstaben",

    games: "Spiele",
    dropzone: ".min hier ablegen oder",
    chooseFiles: "Dateien wählen",
    gamesHint: "Max. Spiele: 20. Max. Dateigröße: 512 KiB.",

    firmware: "Basis-Firmware (UF2)",
    reloadFirmware: "Firmware neu laden",
    chooseAnother: "Andere wählen…",
    fwChecking: "Firmware: wird geprüft…",
    fwLoaded: "Basis-Firmware geladen",
    fwLoadedZip: "Basis-Firmware geladen (zip)",
    fwLoadedZipNoUF2: "ZIP gefunden, aber keine UF2 enthalten",
    fwLocalPage: "Firmware: lokale Seite — Datei manuell wählen",
    fwNotFound: "Basis-Firmware nicht gefunden",
    fwPickManual: "Bitte Firmware manuell auswählen.",
    fwFileProtocolWarning: "Diese Seite wurde lokal geöffnet (file://), der Browser blockiert automatisches Laden. Bitte „Andere wählen…” oder „Neu laden“ verwenden.",

    fwLoadedFrom: "Geladen von",
    fwLoadedDefault: "Geladen",
    fwLoadedManual: "Basis-Firmware geladen (manuell)",
    fwLoadedFile: "Geladen",
    fwFileModeAlert: "Lokale Datei erkannt. Bitte UF2 über „Andere wählen…” oder „Neu laden“ auswählen.",
    fwLoadRequired: "Bitte zuerst Basis-Firmware laden (PM2040.uf2 oder manuell auswählen).",

    gameList: "Spieleliste",
    gameListHint: "Per Ziehen sortieren (≡). Namen können 14 Zeichen überschreiten (werden beim Patchen gekürzt). Fehler werden rot angezeigt.",
    cover: "Cover",
    file: "Datei",
    displayName: "Anzeigename",
    actions: "Aktionen",
    dragToReorder: "Zum Sortieren ziehen",
    remove: "Entfernen",
    charsetHint: "Zeichensatz aktiv; über 14 Zeichen werden beim Patchen abgeschnitten.",

    clear: "Löschen",
    patch: "Patchen",

    footerText: "Erstellt: 2026-06 · Generiert von GPT-5.",

    nameTooShort: "Name muss mindestens 1 Zeichen lang sein.",
    nameTooLong: "Name überschreitet das Limit ({max} Zeichen).",
    charNotAllowed: 'Zeichen "{ch}" ist nicht erlaubt',

    maxGamesReached: "Nur {max} Spiele erlaubt. Zusätzliche Dateien werden ignoriert.",
    fileTooLarge: '"{file}" überschreitet 512 KiB und wurde übersprungen.',
    noGamesAdded: "Mindestens eine .min-Datei hinzufügen.",
    emptyNames: "Einige Namen sind leer.",
    uf2Only: "Nur .uf2-Dateien erlaubt.",
    injectRomMissing: "injectROMs(...) nicht gefunden. Bitte patcher.js einbinden.",
    patchFailed: "Patch fehlgeschlagen. Siehe Konsole.",

    resumeSkip: "[resume-skip]",
    resumePatched: "[resume-patched]"
  },


  //Spanish
  es: {
    appTitle: "PM2040 – Parchador Multi-ROM UF2",
    language: "Idioma",
    theme: "Tema",
    dark: "Oscuro",
    light: "Claro",

    nameSource: "Origen del nombre",
    fromFilename: "Desde archivo",
    fromBinary: "Desde ROM",
    uppercase: "Mayúsculas",

    games: "Juegos",
    dropzone: "Arrastra archivos .min aquí o",
    chooseFiles: "Seleccionar archivos",
    gamesHint: "Máximo 20 juegos. Tamaño máximo: 512 KiB.",

    firmware: "Firmware base (UF2)",
    reloadFirmware: "Recargar firmware",
    chooseAnother: "Elegir otro…",
    fwChecking: "Firmware base: comprobando…",
    fwLoaded: "Firmware base: cargado",
    fwLoadedZip: "Firmware base: cargado (zip)",
    fwLoadedZipNoUF2: "ZIP encontrado pero no hay ningún UF2 dentro",
    fwLocalPage: "Firmware base: página local — selecciona el archivo manualmente",
    fwNotFound: "Firmware base: no encontrado",
    fwPickManual: "Selecciona el firmware manualmente.",
    fwFileProtocolWarning: "Como esta página se abrió desde disco (file://), el navegador bloquea la carga automática. Usa “Elegir otro…” o “Recargar” para seleccionar PM2040.uf2.",

    fwLoadedFrom: "Cargado desde",
    fwLoadedDefault: "Cargado",
    fwLoadedManual: "Firmware base: cargado (manual)",
    fwLoadedFile: "Cargado",
    fwFileModeAlert: "Detectado modo archivo local. Selecciona un UF2 con “Elegir otro…” o pulsa “Recargar” para abrir el selector.",
    fwLoadRequired: "Carga primero el firmware base (PM2040.uf2 o selección manual).",

    gameList: "Lista de juegos",
    gameListHint: "Reordena arrastrando el tirador (≡). Los nombres pueden superar los 14 caracteres (se truncarán al generar). El estado inválido se muestra en rojo + pista. Usa el selector global para cambiar todas las fuentes de nombre.",
    cover: "Portada",
    file: "Archivo",
    displayName: "Nombre mostrado",
    actions: "Acciones",
    dragToReorder: "Arrastrar para reordenar",
    remove: "Eliminar",
    charsetHint: "Se aplica un conjunto de caracteres. Se permite visualizar más de 14 caracteres, pero se truncarán al generar el parche.",

    clear: "Limpiar",
    patch: "Generar",

    footerText: "Creado: 2026-06 · Generado por GPT-5.",

    nameTooShort: "El nombre debe tener al menos 1 carácter.",
    nameTooLong: "El nombre excede el límite (se truncará).",
    charNotAllowed: "Carácter no permitido",

    maxGamesReached: "Solo puedes añadir hasta {max} juegos. Los archivos extra serán ignorados.",
    fileTooLarge: '"{file}" supera 512 KiB y se ha omitido.',
    noGamesAdded: "Añade al menos un juego .min.",
    emptyNames: "Algunos nombres están vacíos.",
    uf2Only: "Solo se permiten archivos .uf2.",
    injectRomMissing: "injectROMs(...) no encontrado. Incluye patcher.js antes de este script de interfaz.",
    patchFailed: "Falló el parcheo. Consulta la consola para más detalles.",

    resumeSkip: "[resume-skip]",
    resumePatched: "[resume-patched]"
  },


  //French
  fr: {
    appTitle: "PM2040 – Patcher Multi-ROM UF2",
    language: "Langue",
    theme: "Thème",
    dark: "Sombre",
    light: "Clair",

    nameSource: "Source du nom",
    fromFilename: "Depuis le fichier",
    fromBinary: "Depuis la ROM",
    uppercase: "Majuscules",

    games: "Jeux",
    dropzone: "Glissez-déposez des fichiers .min ici ou",
    chooseFiles: "Choisir des fichiers",
    gamesHint: "Max jeux : 20. Taille max : 512 KiB.",

    firmware: "Firmware de base (UF2)",
    reloadFirmware: "Recharger le firmware",
    chooseAnother: "Choisir un autre…",
    fwChecking: "Firmware : vérification…",
    fwLoaded: "Firmware de base : chargé",
    fwLoadedZip: "Firmware de base : chargé (zip)",
    fwLoadedZipNoUF2: "ZIP trouvé mais aucun UF2 dedans",
    fwLocalPage: "Firmware : page locale — sélection manuelle requise",
    fwNotFound: "Firmware de base : introuvable",
    fwPickManual: "Veuillez sélectionner le firmware manuellement.",
    fwFileProtocolWarning: "Cette page est ouverte depuis le disque (file://), le navigateur bloque le chargement automatique. Cliquez sur “Choisir un autre…” ou “Recharger”.",

    fwLoadedFrom: "Chargé depuis",
    fwLoadedDefault: "Chargé",
    fwLoadedManual: "Firmware de base : chargé (manuel)",
    fwLoadedFile: "Chargé",
    fwFileModeAlert: "Fichier local détecté. Veuillez choisir un UF2 via “Choisir un autre…” ou “Recharger”.",
    fwLoadRequired: "Chargez d'abord le firmware de base (PM2040.uf2 ou sélection manuelle).",

    gameList: "Liste des jeux",
    gameListHint: "Réorganisez en glissant la poignée (≡). Les noms peuvent dépasser 14 caractères (tronqués lors du patch). Les erreurs sont affichées en rouge.",
    cover: "Couverture",
    file: "Fichier",
    displayName: "Nom affiché",
    actions: "Actions",
    dragToReorder: "Glisser pour réordonner",
    remove: "Supprimer",
    charsetHint: "Jeu de caractères appliqué ; au-delà de 14 caractères, le nom sera tronqué.",

    clear: "Effacer",
    patch: "Patcher",

    footerText: "Créé : 2026-06 · Généré par GPT-5.",

    nameTooShort: "Le nom doit contenir au moins 1 caractère.",
    nameTooLong: "Le nom dépasse la limite ({max} caractères).",
    charNotAllowed: 'Caractère "{ch}" non autorisé',

    maxGamesReached: "Vous ne pouvez ajouter que {max} jeux. Les fichiers supplémentaires seront ignorés.",
    fileTooLarge: '"{file}" dépasse 512 KiB et a été ignoré.',
    noGamesAdded: "Ajoutez au moins un fichier .min.",
    emptyNames: "Certains noms sont vides.",
    uf2Only: "Seuls les fichiers .uf2 sont autorisés.",
    injectRomMissing: "injectROMs(...) introuvable. Ajoutez patcher.js avant ce script UI.",
    patchFailed: "Échec du patch. Voir la console.",

    resumeSkip: "[resume-skip]",
    resumePatched: "[resume-patched]"
  },


  //Italian
  it: {
    // ===== App / header =====
    appTitle: "PM2040 – Patch UF2 Multi-ROM",
    language: "Lingua",
    theme: "Tema",
    dark: "Scuro",
    light: "Chiaro",

    // ===== Settings =====
    nameSource: "Origine nome",
    fromFilename: "Da nome file",
    fromBinary: "Da binario",
    uppercase: "Maiuscolo",

    // ===== Games section =====
    games: "Giochi",
    dropzone: ".min trascina qui o",
    chooseFiles: "Seleziona file",
    gamesHint: "Max 20 giochi. Max 512 KiB per file.",

    // ===== Firmware =====
    firmware: "Firmware base (UF2)",
    reloadFirmware: "Ricarica firmware",
    chooseAnother: "Scegli altro…",
    fwChecking: "Controllo firmware…",
    fwLoaded: "Firmware caricato",
    fwLoadedZip: "Firmware caricato (zip)",
    fwLoadedZipNoUF2: "ZIP senza UF2",
    fwLocalPage: "Pagina locale — selezione manuale",
    fwNotFound: "Firmware non trovato",
    fwPickManual: "Seleziona il firmware manualmente.",
    fwFileProtocolWarning: "File locale rilevato (file://), caricamento automatico bloccato.",

    fwLoadedFrom: "Caricato da",
    fwLoadedDefault: "Caricato",
    fwLoadedManual: "Firmware caricato (manuale)",
    fwLoadedFile: "Caricato",
    fwFileModeAlert: "Modalità file rilevata. Seleziona un UF2 o ricarica.",

    fwLoadRequired: "Carica prima il firmware base.",

    // ===== Game list =====
    gameList: "Lista giochi",
    gameListHint: "Trascina per riordinare (≡).",
    cover: "Copertina",
    file: "File",
    displayName: "Nome visualizzato",
    actions: "Azioni",
    dragToReorder: "Trascina per riordinare",
    remove: "Rimuovi",
    charsetHint: "Limite caratteri 14, troncamento in fase di patch.",

    // ===== Buttons =====
    clear: "Svuota",
    patch: "Genera",

    // ===== Footer =====
    footerText: "Creato: 2026-06 · Generato da GPT-5.",

    // ===== Validation / alerts =====
    nameTooShort: "Il nome deve avere almeno 1 carattere.",
    nameTooLong: "Nome troppo lungo (verrà troncato).",
    charNotAllowed: 'Carattere "{ch}" non consentito.',

    maxGamesReached: "Puoi aggiungere al massimo {max} giochi.",
    fileTooLarge: '"{file}" supera 512 KiB ed è stato ignorato.',
    noGamesAdded: "Aggiungi almeno un gioco .min.",
    emptyNames: "Alcuni nomi sono vuoti.",
    uf2Only: "Sono consentiti solo file .uf2.",
    injectRomMissing: "injectROMs(...) non trovato.",
    patchFailed: "Errore durante il patch.",

    resumeSkip: "[saltato]",
    resumePatched: "[patchato]"
  },


  //Japanese
  ja: {
    appTitle: "PM2040 – UF2 マルチROM パッチャー",
    language: "言語",
    theme: "テーマ",
    dark: "ダーク",
    light: "ライト",

    nameSource: "名前の取得元",
    fromFilename: "ファイル名から",
    fromBinary: "ROMから",
    uppercase: "大文字",

    games: "ゲーム",
    dropzone: ".minをドロップ または",
    chooseFiles: "ファイルを選択",
    gamesHint: "最大20ゲーム。最大サイズ: 512 KiB。",

    firmware: "ベースファームウェア (UF2)",
    reloadFirmware: "再読み込み",
    chooseAnother: "別のファイルを選択…",
    fwChecking: "ファームウェア確認中…",
    fwLoaded: "ベースファームウェア読み込み完了",
    fwLoadedZip: "ベースファームウェア読み込み完了 (zip)",
    fwLoadedZipNoUF2: "ZIP内にUF2が見つかりません",
    fwLocalPage: "ローカルページ検出 — 手動で選択してください",
    fwNotFound: "ベースファームウェアが見つかりません",
    fwPickManual: "ファームウェアを手動で選択してください。",
    fwFileProtocolWarning: "このページはローカル(file://)から開かれています。自動読み込みはブロックされます。「別のファイル」または「再読み込み」を使用してください。",

    fwLoadedFrom: "読み込み元",
    fwLoadedDefault: "読み込み完了",
    fwLoadedManual: "ベースファームウェア読み込み完了（手動）",
    fwLoadedFile: "読み込み完了",
    fwFileModeAlert: "ローカルファイル検出。「別のファイル」または「再読み込み」でUF2を選択してください。",
    fwLoadRequired: "まずベースファームウェアを読み込んでください（PM2040.uf2または手動選択）。",

    gameList: "ゲームリスト",
    gameListHint: "ドラッグで並び替え（≡）。名前は14文字を超える場合があります（パッチ時に切り詰め）。エラーは赤で表示されます。",
    cover: "カバー",
    file: "ファイル",
    displayName: "表示名",
    actions: "操作",
    dragToReorder: "ドラッグで並び替え",
    remove: "削除",
    charsetHint: "文字セット適用済み。14文字を超える場合はパッチ時に切り詰められます。",

    clear: "クリア",
    patch: "パッチ",

    footerText: "作成: 2026-06 · GPT-5 により生成",

    nameTooShort: "名前は1文字以上である必要があります。",
    nameTooLong: "名前が制限を超えています（切り詰められます）。",
    charNotAllowed: '文字 "{ch}" は使用できません。',

    maxGamesReached: "追加できるゲームは最大{max}個です。超過分は無視されます。",
    fileTooLarge: '"{file}" は512 KiBを超えているためスキップされました。',
    noGamesAdded: "少なくとも1つの.minゲームを追加してください。",
    emptyNames: "空の名前があります。",
    uf2Only: ".uf2ファイルのみ使用できます。",
    injectRomMissing: "injectROMs(...) が見つかりません。patcher.jsを読み込んでください。",
    patchFailed: "パッチに失敗しました。コンソールを確認してください。",

    resumeSkip: "[resume-skip]",
    resumePatched: "[resume-patched]"
  },


  //Dutch
  nl: {
    // ===== App / header =====
    appTitle: "PM2040 – UF2 Multi-ROM Patcher",
    language: "Taal",
    theme: "Thema",
    dark: "Donker",
    light: "Licht",

    // ===== Settings =====
    nameSource: "Naambron",
    fromFilename: "Van bestandsnaam",
    fromBinary: "Van binaire data",
    uppercase: "Hoofdletters",

    // ===== Games section =====
    games: "Games",
    dropzone: ".sleep .min bestanden hier of",
    chooseFiles: "Bestanden kiezen",
    gamesHint: "Max 20 games. Max bestandsgrootte: 512 KiB.",

    // ===== Firmware =====
    firmware: "Basisfirmware (UF2)",
    reloadFirmware: "Firmware herladen",
    chooseAnother: "Kies een andere…",
    fwChecking: "Firmware controleren…",
    fwLoaded: "Firmware geladen",
    fwLoadedZip: "Firmware geladen (zip)",
    fwLoadedZipNoUF2: "ZIP gevonden maar geen UF2 erin",
    fwLocalPage: "Lokale modus — kies bestand handmatig",
    fwNotFound: "Firmware niet gevonden",
    fwPickManual: "Kies handmatig een firmwarebestand",
    fwFileProtocolWarning: "Bestandspagina (file://) blokkeert automatisch laden",

    // ===== Game list =====
    gameList: "Gamelijst",
    gameListHint: "Sleep om te sorteren. Namen kunnen >14 tekens zijn (worden afgekapt)",
    cover: "Cover",
    file: "Bestand",
    displayName: "Weergavenaam",
    nameSource: "Naambron",
    actions: "Acties",

    // ===== Buttons =====
    charsetHint: "Tekenset wordt afgedwongen",
    clear: "Wissen",
    patch: "Patchen",

    // ===== Footer =====
    footerText: "Gemaakt: 2026-06 · Generated by GPT-5.",

    // ===== Validation =====
    nameTooShort: "Naam moet minstens 1 teken zijn",
    nameTooLong: "Naam is te lang (wordt afgekapt)",
    invalidChar: "Ongeldig teken",

    // ===== Alerts / runtime =====
    maxGamesAlert: "Je kunt nog {n} games toevoegen",
    fileTooLarge: '"{file}" is te groot en is overgeslagen',
    noGames: "Voeg minstens 1 .min game toe",
    emptyNames: "Sommige namen zijn leeg",

    onlyUF2: "Alleen .uf2 bestanden toegestaan",
    loadFirmwareFirst: "Laad eerst firmware",

    resumeSkip: "[overslaan]",
    resumePatched: "[gepacht]"
  },


  //Polish
  pl: {
    // ===== App / header =====
    appTitle: "PM2040 – Patch UF2 Multi-ROM",
    language: "Język",
    theme: "Motyw",
    dark: "Ciemny",
    light: "Jasny",

    // ===== Settings =====
    nameSource: "Źródło nazwy",
    fromFilename: "Z nazwy pliku",
    fromBinary: "Z binarnego",
    uppercase: "Wielkie litery",

    // ===== Games section =====
    games: "Gry",
    dropzone: ".min przeciągnij tutaj lub",
    chooseFiles: "Wybierz pliki",
    gamesHint: "Maks. 20 gier. Maks. 512 KiB na plik.",

    // ===== Firmware =====
    firmware: "Firmware bazowy (UF2)",
    reloadFirmware: "Przeładuj firmware",
    chooseAnother: "Wybierz inny…",
    fwChecking: "Sprawdzanie firmware…",
    fwLoaded: "Firmware załadowany",
    fwLoadedZip: "Firmware z ZIP",
    fwLoadedZipNoUF2: "Brak UF2 w ZIP",
    fwLocalPage: "Strona lokalna — wybór ręczny",
    fwNotFound: "Nie znaleziono firmware",
    fwPickManual: "Wybierz firmware ręcznie.",
    fwFileProtocolWarning: "Wykryto plik lokalny (file://), automatyczne ładowanie zablokowane.",

    fwLoadedFrom: "Załadowano z",
    fwLoadedDefault: "Załadowano",
    fwLoadedManual: "Firmware (ręcznie)",
    fwLoadedFile: "Załadowano",
    fwFileModeAlert: "Wykryto tryb lokalny. Wybierz UF2 lub przeładuj.",

    fwLoadRequired: "Najpierw załaduj firmware bazowy.",

    // ===== Game list =====
    gameList: "Lista gier",
    gameListHint: "Przeciągnij, aby zmienić kolejność (≡).",
    cover: "Okładka",
    file: "Plik",
    displayName: "Nazwa wyświetlana",
    actions: "Akcje",
    dragToReorder: "Przeciągnij, aby zmienić kolejność",
    remove: "Usuń",
    charsetHint: "Limit 14 znaków, przy patchowaniu następuje obcięcie.",

    // ===== Buttons =====
    clear: "Wyczyść",
    patch: "Generuj",

    // ===== Footer =====
    footerText: "Utworzono: 2026-06 · Wygenerowane przez GPT-5.",

    // ===== Validation / alerts =====
    nameTooShort: "Nazwa musi mieć co najmniej 1 znak.",
    nameTooLong: "Nazwa zbyt długa (zostanie obcięta).",
    charNotAllowed: 'Znak "{ch}" jest niedozwolony.',

    maxGamesReached: "Możesz dodać maksymalnie {max} gier.",
    fileTooLarge: '"{file}" przekracza 512 KiB i został pominięty.',
    noGamesAdded: "Dodaj co najmniej jedną grę .min.",
    emptyNames: "Niektóre nazwy są puste.",
    uf2Only: "Dozwolone tylko pliki .uf2.",
    injectRomMissing: "Nie znaleziono injectROMs(...).",
    patchFailed: "Błąd patchowania.",

    resumeSkip: "[pominięto]",
    resumePatched: "[spatchowane]"
  },


  //Portuguese
  pt: {
    appTitle: "PM2040 – Patch UF2 Multi-ROM",
    language: "Idioma",
    theme: "Tema",
    dark: "Escuro",
    light: "Claro",

    nameSource: "Origem do nome",
    fromFilename: "Do nome do arquivo",
    fromBinary: "Do binário",
    uppercase: "Maiúsculas",

    games: "Jogos",
    dropzone: "Arraste .min aqui ou",
    chooseFiles: "Selecionar arquivos",
    gamesHint: "Máx. 20 jogos. Máx. 512 KiB.",

    firmware: "Firmware base (UF2)",
    reloadFirmware: "Recarregar firmware",
    chooseAnother: "Escolher outro…",
    fwChecking: "Verificando firmware…",
    fwLoaded: "Firmware carregado",
    fwLoadedZip: "Firmware carregado (zip)",
    fwLoadedZipNoUF2: "ZIP sem UF2",
    fwLocalPage: "Página local — seleção manual",
    fwNotFound: "Firmware não encontrado",
    fwPickManual: "Selecione o firmware manualmente.",
    fwFileProtocolWarning: "Arquivo local detectado, carregamento automático bloqueado.",

    fwLoadedFrom: "Carregado de",
    fwLoadedDefault: "Carregado",
    fwLoadedManual: "Firmware carregado (manual)",
    fwLoadedFile: "Carregado",

    fwLoadRequired: "Carregue o firmware primeiro.",

    gameList: "Lista de jogos",
    gameListHint: "Arraste para reordenar.",
    cover: "Capa",
    file: "Arquivo",
    displayName: "Nome exibido",
    actions: "Ações",
    dragToReorder: "Arrastar para ordenar",
    remove: "Remover",
    charsetHint: "Limitado a 14 caracteres.",

    clear: "Limpar",
    patch: "Gerar patch",

    footerText: "Criado: 2026-06 · Gerado por GPT-5.",

    nameTooShort: "Nome precisa ter pelo menos 1 caractere.",
    nameTooLong: "Nome muito longo (será truncado).",
    charNotAllowed: 'Caractere "{ch}" não permitido.',

    maxGamesReached: "Máximo de {max} jogos.",
    fileTooLarge: '"{file}" excede 512 KiB.',
    noGamesAdded: "Adicione pelo menos um jogo.",
    emptyNames: "Há nomes vazios.",
    uf2Only: "Apenas arquivos .uf2.",
    injectRomMissing: "injectROMs(...) não encontrado.",
    patchFailed: "Falha no patch.",

    resumeSkip: "[ignorado]",
    resumePatched: "[aplicado]"
  },


  //Thai
  th: {
    // ===== App / header =====
    appTitle: "PM2040 – UF2 Multi-ROM แพตช์เชอร์",
    language: "ภาษา",
    theme: "ธีม",
    dark: "มืด",
    light: "สว่าง",

    // ===== Settings =====
    nameSource: "แหล่งที่มาชื่อ",
    fromFilename: "จากชื่อไฟล์",
    fromBinary: "จากไบนารี",
    uppercase: "ตัวพิมพ์ใหญ่",

    // ===== Games section =====
    games: "เกม",
    dropzone: ".min ลากมาวางที่นี่ หรือ",
    chooseFiles: "เลือกไฟล์",
    gamesHint: "สูงสุด 20 เกม ไฟล์ละไม่เกิน 512 KiB",

    // ===== Firmware =====
    firmware: "เฟิร์มแวร์ฐาน (UF2)",
    reloadFirmware: "โหลดใหม่",
    chooseAnother: "เลือกไฟล์อื่น…",
    fwChecking: "กำลังตรวจสอบเฟิร์มแวร์…",
    fwLoaded: "โหลดเฟิร์มแวร์แล้ว",
    fwLoadedZip: "โหลดจาก ZIP แล้ว",
    fwLoadedZipNoUF2: "ไม่พบ UF2 ใน ZIP",
    fwLocalPage: "หน้าโลคัล — เลือกไฟล์เอง",
    fwNotFound: "ไม่พบเฟิร์มแวร์",
    fwPickManual: "กรุณาเลือกเฟิร์มแวร์ด้วยตนเอง",
    fwFileProtocolWarning: "ตรวจพบโหมดไฟล์โลคัล (file://) การโหลดอัตโนมัติถูกบล็อก",

    fwLoadedFrom: "โหลดจาก",
    fwLoadedDefault: "โหลดแล้ว",
    fwLoadedManual: "โหลดเฟิร์มแวร์แบบแมนนวล",
    fwLoadedFile: "โหลดแล้ว",
    fwFileModeAlert: "ตรวจพบโหมดโลคัล กรุณาเลือก UF2 หรือโหลดใหม่",

    fwLoadRequired: "กรุณาโหลดเฟิร์มแวร์ก่อน",

    // ===== Game list =====
    gameList: "รายชื่อเกม",
    gameListHint: "ลากเพื่อจัดลำดับ (≡)",
    cover: "ภาพปก",
    file: "ไฟล์",
    displayName: "ชื่อที่แสดง",
    actions: "การทำงาน",
    dragToReorder: "ลากเพื่อจัดลำดับ",
    remove: "ลบ",
    charsetHint: "จำกัด 14 ตัวอักษร (จะถูกตัดตอนแพตช์)",

    // ===== Buttons =====
    clear: "ล้าง",
    patch: "สร้างแพตช์",

    // ===== Footer =====
    footerText: "สร้าง: 2026-06 · สร้างโดย GPT-5",

    // ===== Validation / alerts =====
    nameTooShort: "ชื่อต้องมีอย่างน้อย 1 ตัวอักษร",
    nameTooLong: "ชื่อยาวเกินไป (จะถูกตัด)",
    charNotAllowed: 'ไม่อนุญาตตัวอักษร "{ch}"',

    maxGamesReached: "เพิ่มได้สูงสุด {max} เกม",
    fileTooLarge: '"{file}" เกิน 512 KiB และถูกข้าม',
    noGamesAdded: "กรุณาเพิ่มไฟล์ .min อย่างน้อย 1 ไฟล์",
    emptyNames: "มีชื่อว่างอยู่",
    uf2Only: "รองรับเฉพาะไฟล์ .uf2",
    injectRomMissing: "ไม่พบ injectROMs(...)",
    patchFailed: "การแพตช์ล้มเหลว",

    resumeSkip: "[ข้าม]",
    resumePatched: "[แพตช์แล้ว]"
  },


  //Chinese
  zh: {
    // ===== App / header =====
    appTitle: "PM2040 – UF2 多ROM补丁工具",
    language: "语言",
    theme: "主题",
    dark: "深色",
    light: "浅色",

    // ===== Settings =====
    nameSource: "名称来源",
    fromFilename: "来自文件名",
    fromBinary: "来自二进制",
    uppercase: "大写",

    // ===== Games section =====
    games: "游戏",
    dropzone: ".min 拖放或",
    chooseFiles: "选择文件",
    gamesHint: "最多20个游戏，单文件最大512 KiB。",

    // ===== Firmware =====
    firmware: "基础固件 (UF2)",
    reloadFirmware: "重新加载",
    chooseAnother: "选择其他…",
    fwChecking: "正在检查固件…",
    fwLoaded: "固件已加载",
    fwLoadedZip: "已从ZIP加载固件",
    fwLoadedZipNoUF2: "ZIP中未找到UF2",
    fwLocalPage: "本地页面 — 手动选择",
    fwNotFound: "未找到固件",
    fwPickManual: "请手动选择固件。",
    fwFileProtocolWarning: "本地文件模式（file://），自动加载被阻止。",

    fwLoadedFrom: "加载来源",
    fwLoadedDefault: "已加载",
    fwLoadedManual: "手动加载固件",
    fwLoadedFile: "已加载",
    fwFileModeAlert: "检测到本地模式，请选择UF2或重新加载。",

    fwLoadRequired: "请先加载基础固件。",

    // ===== Game list =====
    gameList: "游戏列表",
    gameListHint: "拖动排序（≡）。",
    cover: "封面",
    file: "文件",
    displayName: "显示名称",
    actions: "操作",
    dragToReorder: "拖动排序",
    remove: "删除",
    charsetHint: "字符集限制，超过14字符会被截断。",

    // ===== Buttons =====
    clear: "清空",
    patch: "生成",

    // ===== Footer =====
    footerText: "创建: 2026-06 · GPT-5生成",

    // ===== Validation / alerts =====
    nameTooShort: "名称至少1个字符。",
    nameTooLong: "名称过长（将被截断）。",
    charNotAllowed: '字符 "{ch}" 不允许。',

    maxGamesReached: "最多只能添加{max}个游戏。",
    fileTooLarge: '"{file}" 超过512 KiB，已跳过。',
    noGamesAdded: "请至少添加一个 .min 游戏。",
    emptyNames: "存在空名称。",
    uf2Only: "仅支持 .uf2 文件。",
    injectRomMissing: "未找到 injectROMs(...)。",
    patchFailed: "补丁失败。",

    resumeSkip: "[跳过]",
    resumePatched: "[已修补]"
  },


};